### ISSUE TITLE
Create export account data endpoint

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#696]
**Describe the solution you'd like**
Create a new controller and endpoint to export a user's book data:
- All of the books in their predefined and custom shelves
- All tags, publishers, etc.

**Additional context**
- Be sure to read the contributing guidelines first!
- Discuss your implementation approach with us before we assign you to it
- Branch from `main` and set `main` as the destination branch in your pull request

If you need help with anything, we'll be happy to help you over a [GitHub Q&A discussion](https://github.com/Project-Books/book-project/discussions/categories/q-a) or our [Slack workspace](https://camo.githubusercontent.com/eef8443bce0a2fdc0706ffcd99f91181ac849a4ef423a1ed61386ca0a8b448bb/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f736c61636b2d7465616d626f6f6b70726f6a6563742d3441313534423f6c6f676f3d736c61636b)

This needs to be thoroughly tested.

**Comment by jwlai** [comment]
@knjk04 I'll take this on- 

I'm assuming this will be consumed by an import. Do we have that feature? If not- What do you prefer for the export? JSON, XML, CSV, something else?

**Comment by knjk04** [comment]
@jwlai Thanks, I'll assign you to the issue!

Yes, we have an ImportService that you can use that exports as JSON. If you use our 0.1.0 demo, you can examine the structure of the exported JSON data

**Comment by jwlai** [comment]
@knjk04 Wanted to start this discussion... shortened JSON output here. I'm creating a Serializers for the different objects as needed. Also the structure was just one that should hopefully match the object...  or did you want closer to the GoodRead import? 


I have 2 questions... 
1. Is it acceptable to have a "null" value. 
2. What do you think of the format so far-
```[
   {
      "shelfName":"Did not finish",
      "books":[
         {
            "title":"Origin",
            "edition":"null",
            "recommendedBy":"John",
            "isbn":"null",
            "review":"Must Read Book. Really Enjoyed it",
            "dateStartedReading":"2021-05-11",
            "genre":[
               "PSYCHOLOGY"
            ]
         },
         {
            "title":"Harry Potter and the Philosopher's stone",
            "edition":"null",
            "recommendedBy":"Sally",
            "isbn":"null",
            "review":"Must Read Book. Really Enjoyed it",
            "dateStartedReading":"2021-05-11",
            "genre":[
               "MEMOIR"
            ]
         }
      ]
   }
]```

**Comment by knjk04** [comment]
@jwlai Thanks, this looks good so far and looks similar to what we had before!

> Is it acceptable to have the straight null (i.e. "edition" : null) or would you rather to have a quoted "null" value

Regular null is fine

> What do you think of the format so far-

Could we have a numeric data type `pagesRead`, `numberOfPages` and `yearOfPublications` instead of strings?

**Comment by knjk04** [comment]
@jwlai Could you bring the latest 0.2.0 changes into your feature branch? We've renamed `CustomShelf` to `UserCreatedShelf`

**Comment by knjk04** [comment]
@jwlai Unassigning as we did not hear back from you

**Comment by olusolaa** [comment]
@knjk04 I can take this

**Comment by knjk04** [comment]
@olusolaa Thanks!

**Comment by olusolaa** [comment]
@knjk04, I had issues running the app. It solved now; so I have started working on the task. I should have communicated earlier sorry about that.

**Comment by olusolaa** [comment]
@knjk04 How do I access the export endpoint I just created? If I am to use postman, do I have to log in first with user@user.user and password to prevent access denial? which endpoint will I call to do the login?

**Comment by knjk04** [comment]
> How do I access the export endpoint I just created?

http://localhost:8080/api/export-user-book-data passing in the correct verb, etc. into Postman

> If I am to use postman, do I have to log in first with user@user.user and password to prevent access denial? which endpoint will I call to do the login?

Yes, you'll need to login via the /login POST endpoint. See this guide for more information and feel free to ask any more questions: https://github.com/Project-Books/book-project/wiki/Connecting-to-the-backend-via-Postman

**Comment by olusolaa** [comment]
You mean the output should look like this, and it should contain all the books of the logged in user.



```yaml
[
    {
        "title": "Stardust",
        "numberOfPages": 389,
        "pagesRead": 868,
        "bookGenre": [
            "Mystery"
        ],
        "bookFormat": null,
        "seriesPosition": 7,
        "edition": null,
        "bookRecommendedBy": "Thomas",
        "isbn": null,
        "yearOfPublication": 1994,
        "author": {
            "fullName": "Dan Brown"
        },
        "predefinedShelf": {
            "shelfName": "To read"
        },
        "userCreatedShelf": null,
        "tags": [
            {
                "name": "Tolkien"
            }
        ],
        "publishers": [
            {
                "name": "Scholastic Corporation"
            }
        ],
        "rating": "No rating",
        "dateStartedReading": null,
        "dateFinishedReading": null,
        "bookReview": "Must Read Book. Really Enjoyed it"
    },
  ```
